apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.15.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: loginapi
  name: loginapi
spec:
  ports:
  - name: "5080"
    port: 5080
    targetPort: 8080
  selector:
    io.kompose.service: loginapi
status:
  loadBalancer: {}
