apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.15.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: nginxw
  name: nginxw
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: nginxw
    spec:
      containers:
      - image: nginxw
        name: gateway
        ports:
        - containerPort: 80
        resources: {}
      restartPolicy: Always
status: {}
