apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.15.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: todolistapi
  name: todolistapi
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: todolistapi
    spec:
      containers:
      - image: todolistapi
        name: apitodolist
        ports:
        - containerPort: 8082
        resources: {}
      restartPolicy: Always
status: {}
