apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.15.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: userapi
  name: userapi
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: userapi
    spec:
      containers:
      - image: userapi
        name: apiusers
        ports:
        - containerPort: 8081
        resources: {}
      restartPolicy: Always
status: {}
