version: '3.3'

services:

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"   
    networks:
      - backend
    volumes:
      - mongo-data:/data/db
  
  userapi:
    build: ./packages/apis.bootstrap.users
    ports:
      - "5081:8081"
    networks: 
      - backend
    depends_on: 
      - loginapi
      - mongodb
  
  loginapi:
    build: ./packages/apis.bootstrap.login
    ports:
      - "5080:8080"
    networks: 
      - backend
    depends_on: 
      - mongodb
  
  nginxw:
    build: ./conf/nginx
    restart: always
    ports:
      - "9090:80"
    depends_on: 
      - mongodb
      - loginapi
      - userapi
    networks: 
      - frontend
      - backend

volumes:
  mongo-data:

networks: 
  frontend:
  backend:

# Start-up
#docker-compose up -d
# Close
#docker-compose down

# Delete all containers
#docker rm $(docker ps -a -q)
# Delete all images
#docker rmi $(docker images -q)

#docker exec -i -t b2346ce35464 /bin/bash
