version: '3'

services:

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"   
    networks:
      - backend
    volumes:
      - mongo-data:/data/db
  
  userapi:
    build: ./packages/apis.bootstrap.users
    container_name: apiusers
    ports:
      - "5081:8081"
    networks: 
      - backend
    depends_on: 
      - loginapi
      - mongodb
  
  loginapi:
    build: ./packages/apis.bootstrap.login
    container_name: apilogin
    ports:
      - "5080:8080"
    networks: 
      - backend
    depends_on: 
      - mongodb
  
  todolistapi:
    build: ./packages/apis.bootstrap.todolist
    container_name: apitodolist
    ports:
      - "5082:8082"
    networks: 
      - backend
    depends_on:
      - loginapi 
      - mongodb
  
  nginxw:
    build: ./conf/nginx
    container_name: gateway
    restart: always
    ports:
      - "9090:80"
    depends_on: 
      - mongodb
      - loginapi
      - userapi
      - todolistapi
    networks: 
      - frontend
      - backend
  
volumes:
  mongo-data:

networks: 
  frontend:
  backend:
    driver: bridge

# Start-up
#docker-compose up -d
# Close
#docker-compose down

# Delete all containers
#docker rm $(docker ps -a -q)
# Delete all images
#docker rmi $(docker images -q)

#docker exec -i -t b2346ce35464 /bin/bash

#deploy on Google Cloud Platform using Kubernetes
#gcloud components install kubectl
#gcloud auth configure-docker
#export PROJECT_ID="$(gcloud config get-value project -q)"
#docker build -t eu.gcr.io/${PROJECT_ID}/loginapi:v1 .
#gcloud docker -- push eu.gcr.io/${PROJECT_ID}/loginapi:v1
#glcoud compute zones list <choose zone>
#gcloud container clusters create pmpempowered-cluster --num-nodes=3 --zone=europe-west3-a
#gcloud compute instances list
#kubectl run pmp-apis --image=eu.gcr.io/${PROJECT_ID}/loginapi:v1 --port 5080
#kubectl get pods
#kubectl expose deployment pmp-apis --type=LoadBalancer --port 80 --target-port 5080
#kubectl get service
#kubectl get deployment pmp-apis
# after upload a new image in the repository
#kubectl set image deployment/pmp-apis pmp-apis=eu.gcr.io/${PROJECT_ID}/loginapi:v2
#remove kluster
#kubectl delete service pmp-apis
#gcloud compute forwarding-rules list #check loadbalancer is deleted too
#gcloud container clusters delete pmpempowered-cluster --zone=europe-west3-a
#kompose convert 