version: '3.3'

services:

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"   
    networks:
      - backend
    volumes:
      - mongo-data:/data/db
  
  userapi:
    build: ./packages/apis.bootstrap.users
    container_name: apiusers
    ports:
      - "5081:8081"
    networks: 
      - backend
    depends_on: 
      - loginapi
      - mongodb
  
  loginapi:
    build: ./packages/apis.bootstrap.login
    container_name: apilogin
    ports:
      - "5080:8080"
    networks: 
      - backend
    depends_on: 
      - mongodb
  
  todolistapi:
    build: ./packages/apis.bootstrap.todolist
    container_name: apitodolist
    ports:
      - "5082:8082"
    networks: 
      - backend
    depends_on:
      - loginapi 
      - mongodb
  
  nginxw:
    build: ./conf/nginx
    container_name: gateway
    restart: always
    ports:
      - "9090:80"
    depends_on: 
      - mongodb
      - loginapi
      - userapi
      - todolistapi
    networks: 
      - frontend
      - backend
  
volumes:
  mongo-data:

networks: 
  frontend:
  backend:
    driver: bridge

# Start-up
#docker-compose up -d
# Close
#docker-compose down

# Delete all containers
#docker rm $(docker ps -a -q)
# Delete all images
#docker rmi $(docker images -q)

#docker exec -i -t b2346ce35464 /bin/bash
